set_family {SmartFusion2}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreResetP\7.1.100\rtl\vhdl\core\coreresetp_pcie_hotreset.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreResetP\7.1.100\rtl\vhdl\core\coreresetp.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CCC_0\SF2_MSS_sys_sb_CCC_0_FCCC.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\FABOSC_0\SF2_MSS_sys_sb_FABOSC_0_OSC.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\IO_0\SF2_MSS_sys_sb_IO_0_IO.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\IO_1\SF2_MSS_sys_sb_IO_1_IO.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb_MSS\SF2_MSS_sys_sb_MSS.vhd}
read_vhdl -mode vhdl_2008 -lib COREAPB3_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vhdl\core\coreapb3_muxptob3.vhd}
read_vhdl -mode vhdl_2008 -lib COREAPB3_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vhdl\core\coreapb3_iaddr_reg.vhd}
read_vhdl -mode vhdl_2008 -lib COREAPB3_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vhdl\core\coreapb3.vhd}
read_vhdl -mode vhdl_2008 -lib COREGPIO_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreGPIO\3.1.101\rtl\vhdl\core\coregpio_pkg.vhd}
read_vhdl -mode vhdl_2008 -lib COREGPIO_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreGPIO\3.1.101\rtl\vhdl\core\coregpio.vhd}
read_vhdl -mode vhdl_2008 -lib COREI2C_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\COREI2C\7.2.101\rtl\vhdl\core\corei2creal.vhd}
read_vhdl -mode vhdl_2008 -lib COREI2C_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\COREI2C_0\rtl\vhdl\core\corei2c.vhd}
read_vhdl -mode vhdl_2008 -lib COREPWM_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\corepwm\4.3.101\rtl\vhdl\core\pwm_gen.vhd}
read_vhdl -mode vhdl_2008 -lib COREPWM_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\corepwm\4.3.101\rtl\vhdl\core\reg_if.vhd}
read_vhdl -mode vhdl_2008 -lib COREPWM_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\corepwm\4.3.101\rtl\vhdl\core\tach_if.vhd}
read_vhdl -mode vhdl_2008 -lib COREPWM_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\corepwm\4.3.101\rtl\vhdl\core\timebase.vhd}
read_vhdl -mode vhdl_2008 -lib COREPWM_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\corepwm\4.3.101\rtl\vhdl\core\t_corepwm_pkg.vhd}
read_vhdl -mode vhdl_2008 -lib COREPWM_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\corepwm\4.3.101\rtl\vhdl\core\corepwm.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\spi_clockmux.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\corespi_pkg.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\spi_chanctrl.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\spi_control.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\spi_fifo.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\spi_rf.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\spi.vhd}
read_vhdl -mode vhdl_2008 -lib CORESPI_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CORESPI\5.1.104\rtl\vhdl\core\corespi.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\Clock_gen.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\Rx_async.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\Tx_async.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\fifo_256x8.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\coreuart_pkg.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\CoreUART.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\CoreUARTapb.vhd}
read_vhdl -mode vhdl_2008 -lib COREAPB3_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vhdl\core\components.vhd}
read_vhdl -mode vhdl_2008 -lib COREGPIO_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\CoreGPIO\3.1.101\rtl\vhdl\core\components.vhd}
read_vhdl -mode vhdl_2008 -lib COREPWM_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\Actel\DirectCore\corepwm\4.3.101\rtl\vhdl\core\components.vhd}
read_vhdl -mode vhdl_2008 -lib COREUARTAPB_LIB {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\CoreUARTapb_0\rtl\vhdl\core\components.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys_sb\SF2_MSS_sys_sb.vhd}
read_vhdl -mode vhdl_2008 {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\component\work\SF2_MSS_sys\SF2_MSS_sys.vhd}
set_top_level {SF2_MSS_sys}
map_netlist
read_sdc {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\constraint\SF2_MSS_sys_derived_constraints.sdc}
check_constraints {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\constraint\synthesis_sdc_errors.log}
write_fdc {C:\Users\Mike Klopfer\Documents\GitHub\Microsemi_SmartFusion2_FutureCreativeBoard_BaseDesign\FCBBaseDesign\designer\SF2_MSS_sys\synthesis.fdc}
